// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANF2FNJ-RWrx4IWat7fKyzA1qKWk30Xk8',
    appId: '1:296437325216:web:4654ab9a3e9f6b141558c5',
    messagingSenderId: '296437325216',
    projectId: 'sisop-rs',
    authDomain: 'sisop-rs.firebaseapp.com',
    storageBucket: 'sisop-rs.appspot.com',
    measurementId: 'G-X7HS9ZQXKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB185xF9nlG7Sq--wQUZMN85YEKPt6BOQo',
    appId: '1:296437325216:android:6d5c4661f1df16e91558c5',
    messagingSenderId: '296437325216',
    projectId: 'sisop-rs',
    storageBucket: 'sisop-rs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8kRG64fa50TwmQSqyNZfZ4cgSZsggr8',
    appId: '1:296437325216:ios:d18ef2d8e47238c71558c5',
    messagingSenderId: '296437325216',
    projectId: 'sisop-rs',
    storageBucket: 'sisop-rs.appspot.com',
    iosBundleId: 'com.example.registroici',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ8kRG64fa50TwmQSqyNZfZ4cgSZsggr8',
    appId: '1:296437325216:ios:df40051c006423da1558c5',
    messagingSenderId: '296437325216',
    projectId: 'sisop-rs',
    storageBucket: 'sisop-rs.appspot.com',
    iosBundleId: 'com.example.registroici.RunnerTests',
  );
}
